### ISSUE TITLE
建议可以批量更改变量名

### ISSUE THREAD

**Issue by Tlntin** [gauseen/vscode-string-transform#8]
测试了一下，只能更改选中的变量名，但是其它同名变量不会进行更改，导致效率较低，实际体验不如直接选中按F2来的方便。
建议增加：
1. 变量更改快捷键，而不是ctrl+shift+p 再to xxx。
2. 增加同名变量全文更改，类似vscode的F2功能，只要是该变量都修改。
3. 增加同类变量风格修改，比如我选择了变量A，它是小驼峰，B变量如果也是小驼峰的话，也会进行格式修改。而不是一个个去选择A, B。

**Comment by gauseen** [comment]
@Tlntin 感谢提的建议

1. 因为有很多种命名方式，如果每种命名都增加对应的快捷键，就导致存在很多快捷键，不容易记忆。如果只有一个快捷键，那就要一个个轮流转换，反而会效率低。目前支持按住 option 键，选中多个变量，一起修改
2. 因为项目代码是比较复杂的，如果默认全局更改相同变量，可能会导致预期外的修改，导致出现 bug，建议用 vscode 全局替换功能
3. 也是跟 2 同样的情况，尽量避免对用户无感知的修改
